### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by yusufobr** [RHK-MICROVERSE/Books-Awesome#2]
Hello @RHK-MICROVERSE , 
To make your code more readable and easier to understand, I suggest you attach this function to an event listener. In this case, DOMContentLoaded would be appropriate.  🙏
https://github.com/RHK-MICROVERSE/Books-Awesome/blob/81074737810d446ad9f56e58e403eacc8d809c36/book.js#L48

**Comment by fickryiman** [comment]
this line function is  use on window first load, as similar if we put it on window.onload event listener
